/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoMidnightBlueIJTheme;
/**
 *
 * @author Alumno
 */
public class amigos extends javax.swing.JFrame {

    /**
     * Creates new form amigos
     */
    public amigos() {
        initComponents();
        atras.setIcon(new FlatSVGIcon( "image/atras.svg" ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelamigos = new javax.swing.JPanel();
        Listaamigos = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        agregar = new javax.swing.JButton();
        panellogo = new javax.swing.JPanel();
        Atras = new javax.swing.JPanel();
        atras = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelamigos.setBackground(new java.awt.Color(31, 37, 51));

        jList1.setBackground(new java.awt.Color(45, 64, 87));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Listaamigos.setViewportView(jList1);

        agregar.setBackground(new java.awt.Color(25, 30, 42));
        agregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar amigos");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelamigosLayout = new javax.swing.GroupLayout(panelamigos);
        panelamigos.setLayout(panelamigosLayout);
        panelamigosLayout.setHorizontalGroup(
            panelamigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelamigosLayout.createSequentialGroup()
                .addGroup(panelamigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelamigosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelamigosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Listaamigos, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelamigosLayout.setVerticalGroup(
            panelamigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelamigosLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(Listaamigos, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(panelamigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 420, 430));

        panellogo.setBackground(new java.awt.Color(44, 47, 72));
        panellogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Atras.setBackground(new java.awt.Color(44, 47, 72));

        atras.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout AtrasLayout = new javax.swing.GroupLayout(Atras);
        Atras.setLayout(AtrasLayout);
        AtrasLayout.setHorizontalGroup(
            AtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtrasLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(atras, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );
        AtrasLayout.setVerticalGroup(
            AtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtrasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(atras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panellogo.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        panellogo.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(panellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 390, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atras;
    private javax.swing.JLabel Icon;
    private javax.swing.JScrollPane Listaamigos;
    private javax.swing.JButton agregar;
    private javax.swing.JLabel atras;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel panelamigos;
    private javax.swing.JPanel panellogo;
    // End of variables declaration//GEN-END:variables
}
