/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoMidnightBlueIJTheme;
/**
 *
 * @author ALBERTO BARCALA GUTIÉRREZ
 */
public class inicio extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public inicio() {
        setLocationRelativeTo(null);
        initComponents();
        atras.setVisible(false);
        Loging log =new Loging();
        log.setSize(mobil.getWidth(),mobil.getHeight());
        log.setLocation(0,0);
        mobil.removeAll();
        mobil.add(log);
        mobil.revalidate();
        mobil.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mobil = new javax.swing.JPanel();
        fijo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        registrarse = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        contraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mobil.setMinimumSize(new java.awt.Dimension(432, 636));
        mobil.setPreferredSize(new java.awt.Dimension(432, 636));

        javax.swing.GroupLayout mobilLayout = new javax.swing.GroupLayout(mobil);
        mobil.setLayout(mobilLayout);
        mobilLayout.setHorizontalGroup(
            mobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        mobilLayout.setVerticalGroup(
            mobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fijo.setBackground(new java.awt.Color(28, 10, 67));
        fijo.setForeground(new java.awt.Color(28, 10, 67));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        registrarse.setBackground(new java.awt.Color(25, 30, 42));
        registrarse.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        registrarse.setForeground(new java.awt.Color(255, 255, 255));
        registrarse.setText("Registrarse");
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        atras.setBackground(new java.awt.Color(25, 30, 42));
        atras.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atras");
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        contraseña.setBackground(new java.awt.Color(25, 30, 42));
        contraseña.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Restablecer contraseña");
        contraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fijoLayout = new javax.swing.GroupLayout(fijo);
        fijo.setLayout(fijoLayout);
        fijoLayout.setHorizontalGroup(
            fijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(fijoLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(fijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fijoLayout.createSequentialGroup()
                        .addComponent(contraseña)
                        .addGap(24, 24, 24)
                        .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fijoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fijoLayout.setVerticalGroup(
            fijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fijoLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(fijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        atras.setVisible(true);
        contraseña.setVisible(false);
        registrarse.setVisible(false);
        Recu rec= new Recu();
        rec.setSize(mobil.getWidth(),mobil.getHeight());
        rec.setLocation(0,0);
        mobil.removeAll();
        mobil.add(rec);
        mobil.revalidate();
        mobil.repaint();
    }//GEN-LAST:event_contraseñaActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        atras.setVisible(false);
        contraseña.setVisible(true);
        registrarse.setVisible(true);
        Loging log =new Loging();
        log.setSize(mobil.getWidth(),mobil.getHeight());
        log.setLocation(0,0);
        mobil.removeAll();
        mobil.add(log);
        mobil.revalidate();
        mobil.repaint();
    }//GEN-LAST:event_atrasActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        atras.setVisible(true);
        contraseña.setVisible(false);
        registrarse.setVisible(false);
        nuevacuenta nue= new nuevacuenta();
        nue.setSize(mobil.getWidth(),mobil.getHeight());
        nue.setLocation(0,0);
        mobil.removeAll();
        mobil.add(nue);
        mobil.revalidate();
        mobil.repaint();
    }//GEN-LAST:event_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatGradiantoMidnightBlueIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton contraseña;
    private javax.swing.JPanel fijo;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mobil;
    private javax.swing.JButton registrarse;
    // End of variables declaration//GEN-END:variables
}
