/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import com.formdev.flatlaf.ui.FlatRoundBorder;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author Alberto Barcala Gutiérrez
 */
public class juegosdisplay extends javax.swing.JPanel {

	/**
	 * Creates new form juegosdisplay
	 */
	private final String title;
	private final String description;
	private final String creator;
	private final String gameType;

	public juegosdisplay(String titl, String des, String crea, String game) {
		this.title = titl;
		this.description = des;
		this.creator = crea;
		this.gameType = game;
		initComponents();
		setPreferredSize(new Dimension(320, 208));
		setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10)); // Usar FlowLayout en lugar de null layout
		setBackground(new Color(44, 47, 72));
		FlatRoundBorder border = new FlatRoundBorder();
		setBorder(BorderFactory.createCompoundBorder(border, BorderFactory.createEmptyBorder(10, 10, 10, 10)));

		JLabel titleLabel = new JLabel(title);
		titleLabel.setForeground(Color.WHITE);
		add(titleLabel);

		JTextArea descriptionArea = new JTextArea(description);
		descriptionArea.setForeground(new Color(255, 255, 255, 55));
		descriptionArea.setOpaque(false);
		descriptionArea.setEditable(false);
		add(descriptionArea);

		JLabel imagen = new JLabel("");
		add(imagen);

		String iconPath = "/image/" + (gameType.equals("PC") ? "PC.png" : "Consola.png");
		ImageIcon icon = new ImageIcon(getClass().getResource(iconPath));
		imagen.setIcon(icon);

		JLabel creatorLabel = new JLabel("Creador: " + creator);
		creatorLabel.setForeground(Color.WHITE);
		add(creatorLabel);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
}
