/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author alber
 */
import javax.swing.*;
import java.awt.*;

public class juegosdisplay extends JPanel {
    private String title;
    private String description;

    public juegosdisplay(String title, String description) {
        this.title = title;
        this.description = description;

        setPreferredSize(new Dimension(320, 208));
        setLayout(null);  // Usamos un diseño nulo para posicionar los elementos manualmente
        setBackground(new Color(44, 47, 72));
        setBorder(BorderFactory.createRoundedBorder(20));

        JLabel titleLabel = new JLabel(title);
        titleLabel.setBounds(12, 113, 139, 20);
        titleLabel.setForeground(Color.WHITE);
        add(titleLabel);

        JTextArea descriptionArea = new JTextArea(description);
        descriptionArea.setBounds(12, 145, 283, 28);
        descriptionArea.setForeground(new Color(255, 255, 255, 55));
        descriptionArea.setOpaque(false);
        descriptionArea.setEditable(false);
        add(descriptionArea);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Featured Card Example");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        juegosdisplay juego = new juegosdisplay("Your Title", "Your Description");
        frame.add(juego);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
