/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.model;
import hibernate.*;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.util.Iterator;

/**
 *
 * @author ALBERTO BARCALA GUTIÉRREZ
 */
public class PanelInicio extends javax.swing.JPanel {
	private JPanel panelCambia;
	private JPanel panelInformacion;
        Usuario user;
	model model;

	/**
	 * Creates new form PanelInicio
	 */

	public PanelInicio(model model1, Usuario user) {
		this.model = model1;
                this.user=user;
		initComponents();
		panelCambia = new JPanel(new GridLayout(0, 3, 50, 50));
		panelCambia.setBorder(BorderFactory.createEmptyBorder(133, 36, 214, 33));
		Iterator<Juegos> juegosIterator = model.obtenerJuegosComprados(0);
		if (juegosIterator==null) {
			juegosIterator = model.obtenerTodosLosJuegos();
		}
                int i=0;
		// Crear paneles de juegos y agregarlos al panel de juegos
		while (juegosIterator.hasNext()&&i!=3) {
			Juegos juego = juegosIterator.next();
			juegosdisplay juegoss = new juegosdisplay(juego.getNombre(), juego.getDescripcion(), juego.getCreador(),
					juego.getCategoria());
			panelCambia.add(juegoss);
                        i++;
		}
		// Agregar el panel de juegos al panel principal
		panelmenu.add(panelCambia); // Aquí se agrega el panelCambia al panel principal panelmenu

		// Ajustar el tamaño y el espacio alrededor del panelCambia
		panelCambia.setPreferredSize(new Dimension(1063, 208)); // Establecer el tamaño del panelCambia
		panelCambia.setBorder(new EmptyBorder(133, 36, 214, 33)); // Establecer el espacio alrededor del panelCambia

		/*
		 * // Configurar el panel de música panelInformacion = new JPanel();s
		 * panelInformacion.setPreferredSize(new Dimension(1069, 135));
		 * panelInformacion.setBorder(BorderFactory.createEmptyBorder(65, 192, 53,
		 * 600)); List<Musica> musicas = model.obtenerMusicasCompradas(0); for (Musica
		 * musica : musicas) { JPanel musicaPanel = model.crearMusicaPanel(musica);
		 * panelCambia.add(musicaPanel); }
		 */
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		panelmenu = new javax.swing.JPanel();

		panelmenu.setBackground(new java.awt.Color(44, 47, 72));
		panelmenu.setMinimumSize(new java.awt.Dimension(1132, 774));
		panelmenu.setPreferredSize(new java.awt.Dimension(1132, 774));

		javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
		panelmenu.setLayout(panelmenuLayout);
		panelmenuLayout.setHorizontalGroup(panelmenuLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1132, Short.MAX_VALUE));
		panelmenuLayout.setVerticalGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 774, Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelmenu,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelmenu,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
		throw new UnsupportedOperationException("Not supported yet."); // Generated from
																		// nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel panelmenu;
	// End of variables declaration//GEN-END:variables
}
