/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;

/**
 *
 * @author Alumno
 */
class Recu extends javax.swing.JPanel {
    model mod=new model();
    String defN="ejemplo@ejemplo.com",defC="holabuenosdias";
    /**
     * Creates new form Loging
     */
    public Recu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contraseña = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        nombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        correo = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 37, 51));
        setMinimumSize(new java.awt.Dimension(432, 636));
        setPreferredSize(new java.awt.Dimension(432, 636));

        contraseña.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Nueva Contraseña:");

        contra.setBackground(new java.awt.Color(31, 37, 51));
        contra.setForeground(new java.awt.Color(255, 255, 255));
        contra.setText("jPasswordField1");
        contra.setMinimumSize(new java.awt.Dimension(139, 22));
        contra.setPreferredSize(new java.awt.Dimension(139, 22));
        contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraMouseClicked(evt);
            }
        });
        contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraKeyPressed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Correo:");

        Nombre.setBackground(new java.awt.Color(31, 37, 51));
        Nombre.setForeground(new java.awt.Color(204, 204, 204));
        Nombre.setText("ejemplo@ejemplo.com");
        Nombre.setToolTipText("");
        Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreMouseClicked(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreKeyPressed(evt);
            }
        });

        correo.setBackground(new java.awt.Color(25, 30, 42));
        correo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(255, 255, 255));
        correo.setText("Enviar nueva contraseña");
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contraseña)
                            .addComponent(nombre))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(contra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(correo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreMouseClicked
        if(Nombre.getText().equals(defN)){
            Nombre.setText("");
            Nombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_NombreMouseClicked

    private void NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
            correo.requestFocus();
        }
    }//GEN-LAST:event_NombreKeyPressed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        final String fromEmail="alberto.bargut@educa.jcyl.es";
        final String password="salamanca";
        final String toEmail=Nombre.getText();
        Properties props =new Properties();
        props.put("mail.smtp.host", "smtp-mail.outlook.com");
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.port","587");

        Authenticator auth = new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, password);
            }
        };
        Session session = Session.getDefaultInstance(props, auth);
        System.out.println("Session created");
        try {
            String nuevacontraseña=new String (contra.getPassword());
            mod.cambiarContrasena(Nombre.getText(), nuevacontraseña);
            EmailUtil.sendEmail(session, toEmail, "Cambio de contraseña","Tu nueva contraseña es: "+nuevacontraseña+" hasta que la cambies");
        } catch (MessagingException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_correoActionPerformed

    private void contraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraMouseClicked
        if(Nombre.getText().equals("")){
            Nombre.setText(defN);
            Nombre.setForeground(Color.LIGHT_GRAY);
        }
        if(contra.getPassword().equals(defC)){
            contra.setText("");
            contra.setForeground(Color.black);
        }
    }//GEN-LAST:event_contraMouseClicked

    private void contraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
            correo.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_contraKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JPasswordField contra;
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton correo;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
