package hibernate;
// Generated 5 feb 2024 20:20:46 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * Compras generated by hbm2java
 */
public class Compras implements java.io.Serializable {

	private Integer id;
	private Juegos juegos;
	private Usuario usuario;
	private Date fechaCompra;

	public Compras() {
	}

	public Compras(Juegos juegos, Usuario usuario, Date fechaCompra) {
		this.juegos = juegos;
		this.usuario = usuario;
		this.fechaCompra = fechaCompra;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Juegos getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Juegos juegos) {
		this.juegos = juegos;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

}
