package hibernate;
// Generated 29 ene 2024 18:07:53 by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Musica generated by hbm2java
 */
public class Musica implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String creador;
	private Date duracion;
	private String descripcion;
	private Date fechaSalida;
	private String album;
	private Set usuarios = new HashSet(0);
	private Set comprases = new HashSet(0);

	public Musica() {
	}

	public Musica(String nombre, String creador) {
		this.nombre = nombre;
		this.creador = creador;
	}

	public Musica(String nombre, String creador, Date duracion, String descripcion, Date fechaSalida, String album,
			Set usuarios, Set comprases) {
		this.nombre = nombre;
		this.creador = creador;
		this.duracion = duracion;
		this.descripcion = descripcion;
		this.fechaSalida = fechaSalida;
		this.album = album;
		this.usuarios = usuarios;
		this.comprases = comprases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCreador() {
		return this.creador;
	}

	public void setCreador(String creador) {
		this.creador = creador;
	}

	public Date getDuracion() {
		return this.duracion;
	}

	public void setDuracion(Date duracion) {
		this.duracion = duracion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	public String getAlbum() {
		return this.album;
	}

	public void setAlbum(String album) {
		this.album = album;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getComprases() {
		return this.comprases;
	}

	public void setComprases(Set comprases) {
		this.comprases = comprases;
	}

}
