package hibernate;
// Generated 5 feb 2024 20:20:46 by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String username;
	private String contrasenaEncriptada;
	private String correoRecuperacion;
	private Integer edad;
	private Boolean esMenor;
	private String numeroTarjeta;
	private Date fechaExpiracion;
	private Integer codigoSeguridad;
	private Set juegoses = new HashSet(0);
	private Set usuariosForIdUsuario1 = new HashSet(0);
	private Set usuariosForIdUsuario2 = new HashSet(0);
	private Set comprases = new HashSet(0);
	private Set historials = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String username, String contrasenaEncriptada, String correoRecuperacion) {
		this.username = username;
		this.contrasenaEncriptada = contrasenaEncriptada;
		this.correoRecuperacion = correoRecuperacion;
	}

	public Usuario(String username, String contrasenaEncriptada, String correoRecuperacion, Integer edad,
			Boolean esMenor, String numeroTarjeta, Date fechaExpiracion, Integer codigoSeguridad, Set juegoses,
			Set usuariosForIdUsuario1, Set usuariosForIdUsuario2, Set comprases, Set historials) {
		this.username = username;
		this.contrasenaEncriptada = contrasenaEncriptada;
		this.correoRecuperacion = correoRecuperacion;
		this.edad = edad;
		this.esMenor = esMenor;
		this.numeroTarjeta = numeroTarjeta;
		this.fechaExpiracion = fechaExpiracion;
		this.codigoSeguridad = codigoSeguridad;
		this.juegoses = juegoses;
		this.usuariosForIdUsuario1 = usuariosForIdUsuario1;
		this.usuariosForIdUsuario2 = usuariosForIdUsuario2;
		this.comprases = comprases;
		this.historials = historials;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getContrasenaEncriptada() {
		return this.contrasenaEncriptada;
	}

	public void setContrasenaEncriptada(String contrasenaEncriptada) {
		this.contrasenaEncriptada = contrasenaEncriptada;
	}

	public String getCorreoRecuperacion() {
		return this.correoRecuperacion;
	}

	public void setCorreoRecuperacion(String correoRecuperacion) {
		this.correoRecuperacion = correoRecuperacion;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Boolean getEsMenor() {
		return this.esMenor;
	}

	public void setEsMenor(Boolean esMenor) {
		this.esMenor = esMenor;
	}

	public String getNumeroTarjeta() {
		return this.numeroTarjeta;
	}

	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
	}

	public Date getFechaExpiracion() {
		return this.fechaExpiracion;
	}

	public void setFechaExpiracion(Date fechaExpiracion) {
		this.fechaExpiracion = fechaExpiracion;
	}

	public Integer getCodigoSeguridad() {
		return this.codigoSeguridad;
	}

	public void setCodigoSeguridad(Integer codigoSeguridad) {
		this.codigoSeguridad = codigoSeguridad;
	}

	public Set getJuegoses() {
		return this.juegoses;
	}

	public void setJuegoses(Set juegoses) {
		this.juegoses = juegoses;
	}

	public Set getUsuariosForIdUsuario1() {
		return this.usuariosForIdUsuario1;
	}

	public void setUsuariosForIdUsuario1(Set usuariosForIdUsuario1) {
		this.usuariosForIdUsuario1 = usuariosForIdUsuario1;
	}

	public Set getUsuariosForIdUsuario2() {
		return this.usuariosForIdUsuario2;
	}

	public void setUsuariosForIdUsuario2(Set usuariosForIdUsuario2) {
		this.usuariosForIdUsuario2 = usuariosForIdUsuario2;
	}

	public Set getComprases() {
		return this.comprases;
	}

	public void setComprases(Set comprases) {
		this.comprases = comprases;
	}

	public Set getHistorials() {
		return this.historials;
	}

	public void setHistorials(Set historials) {
		this.historials = historials;
	}

}
