package hibernate;
// Generated 30 ene 2024 16:53:44 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String username;
	private String correo;
	private String contrasenaEncriptada;
	private Integer edad;
	private Boolean esMenor;
	private String numeroTarjeta;
	private Integer codigoSeguridad;
	private Set musicas = new HashSet(0);
	private Set juegoses = new HashSet(0);
	private Set usuariosForIdUsuario1 = new HashSet(0);
	private Set usuariosForIdUsuario2 = new HashSet(0);
	private Set comprases = new HashSet(0);
	private Set historials = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String username, String correo, String contrasenaEncriptada) {
		this.username = username;
		this.correo = correo;
		this.contrasenaEncriptada = contrasenaEncriptada;
	}

	public Usuario(String username, String correo, String contrasenaEncriptada, Integer edad, Boolean esMenor,
			String numeroTarjeta, Integer codigoSeguridad, Set musicas, Set juegoses, Set usuariosForIdUsuario1,
			Set usuariosForIdUsuario2, Set comprases, Set historials) {
		this.username = username;
		this.correo = correo;
		this.contrasenaEncriptada = contrasenaEncriptada;
		this.edad = edad;
		this.esMenor = esMenor;
		this.numeroTarjeta = numeroTarjeta;
		this.codigoSeguridad = codigoSeguridad;
		this.musicas = musicas;
		this.juegoses = juegoses;
		this.usuariosForIdUsuario1 = usuariosForIdUsuario1;
		this.usuariosForIdUsuario2 = usuariosForIdUsuario2;
		this.comprases = comprases;
		this.historials = historials;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContrasenaEncriptada() {
		return this.contrasenaEncriptada;
	}

	public void setContrasenaEncriptada(String contrasenaEncriptada) {
		this.contrasenaEncriptada = contrasenaEncriptada;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Boolean getEsMenor() {
		return this.esMenor;
	}

	public void setEsMenor(Boolean esMenor) {
		this.esMenor = esMenor;
	}

	public String getNumeroTarjeta() {
		return this.numeroTarjeta;
	}

	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
	}

	public Integer getCodigoSeguridad() {
		return this.codigoSeguridad;
	}

	public void setCodigoSeguridad(Integer codigoSeguridad) {
		this.codigoSeguridad = codigoSeguridad;
	}

	public Set getMusicas() {
		return this.musicas;
	}

	public void setMusicas(Set musicas) {
		this.musicas = musicas;
	}

	public Set getJuegoses() {
		return this.juegoses;
	}

	public void setJuegoses(Set juegoses) {
		this.juegoses = juegoses;
	}

	public Set getUsuariosForIdUsuario1() {
		return this.usuariosForIdUsuario1;
	}

	public void setUsuariosForIdUsuario1(Set usuariosForIdUsuario1) {
		this.usuariosForIdUsuario1 = usuariosForIdUsuario1;
	}

	public Set getUsuariosForIdUsuario2() {
		return this.usuariosForIdUsuario2;
	}

	public void setUsuariosForIdUsuario2(Set usuariosForIdUsuario2) {
		this.usuariosForIdUsuario2 = usuariosForIdUsuario2;
	}

	public Set getComprases() {
		return this.comprases;
	}

	public void setComprases(Set comprases) {
		this.comprases = comprases;
	}

	public Set getHistorials() {
		return this.historials;
	}

	public void setHistorials(Set historials) {
		this.historials = historials;
	}

}
